server:
  port: 8761

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/useraccount
    username: root
    password: Pr@gm4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: eureka-microservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

appDescription: "Pragma Eureka Server"
appVersion: "1.0.0"
